# fly.toml app configuration file generated for decembermdx on 2023-12-18T11:06:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "decembermdx"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
experimental.auto_rollback = true
allowed_public_ports = []

[env]
PORT = "8080"
NODE_ENV = "production"
PRIMARY_REGION = "ord"

[build]

[deploy]
release_command = "npx prisma migrate deploy"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 200
soft_limit = 150
type = "requests"

[[services.ports]]
handlers = ["http"]

[[services.ports]]
port = "443"
handlers = ["tls", "http"]

[[services.tcp_checks]]
grace_period = "5s"
interval = "15s"
restart_limit = 0
timeout = "5s"
[[services.http_checks]]
interval = 10000
grace_period = 5000
method = "get"
path = "/healthcheck"
protocol = "http"
timeout = 2000
tls_skip_verify = false
[services.http_checks.headers]

[[services.processes]]


[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
